import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Japon Şef Bıçağı",
    description: "Hassas kesim ve üstün dayanıklılık için elde dövülmüş yüksek karbonlu çelik.",
    price: 185,
    category: "Bıçaklar",
    imageUrl: "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&q=80&w=800",
    rating: 5,
  },
  {
    id: "2",
    name: "Döküm Demir Tencere",
    description: "Mükemmel ısı dağılımı ve koruması için emaye kaplı dökme demir.",
    price: 245,
    category: "Pişirme Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1584947848229-45a44c00abf1?auto=format&fit=crop&q=80&w=800",
    rating: 5,
  },
  {
    id: "3",
    name: "Yapışmaz Sote Tavası",
    description: "Zahmetsiz pişirme ve temizlik için profesyonel kalitede toksik olmayan kaplama.",
    price: 125,
    category: "Pişirme Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=800",
    rating: 4,
  },
  {
    id: "4",
    name: "Seramik Yemek Tabağı Seti",
    description: "Organik dokulara sahip 4 adet el yapımı sırlı seramik tabak seti.",
    price: 85,
    category: "Sofra Takımı",
    imageUrl: "https://images.unsplash.com/photo-1591192801546-7037583ee3e8?auto=format&fit=crop&q=80&w=800",
    rating: 5,
  },
  {
    id: "5",
    name: "Paslanmaz Çelik Karıştırma Kapları",
    description: "Kaymaz silikon tabanlı 3'lü iç içe geçebilen set.",
    price: 65,
    category: "Mutfak Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1544333346-60195c6c6460?auto=format&fit=crop&q=80&w=800",
    rating: 4,
  },
  {
    id: "6",
    name: "Bakır Tabanlı Sos Tenceresi",
    description: "Hassas sıcaklık kontrolü için hızlı ısıtma ve soğutma.",
    price: 195,
    category: "Pişirme Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&q=80&w=800",
    rating: 5,
  },
  {
    id: "7",
    name: "Artizan Ekmek Jileti",
    description: "Değiştirilebilir cerrahi çelik bıçaklı şık ceviz sap.",
    price: 35,
    category: "Fırın Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800",
    rating: 5,
  },
  {
    id: "8",
    name: "Ceviz Kesme Tahtası",
    description: "Bıçak kenarlarınızı korumak için uç tahıllı yapı.",
    price: 115,
    category: "Mutfak Gereçleri",
    imageUrl: "https://images.unsplash.com/photo-1614362848413-59750d440058?auto=format&fit=crop&q=80&w=800",
    rating: 4,
  },
];
