import { Product } from "@/types";
import { categoryMap } from "./categories";
import { slugify } from "./utils";
import productImages from "./productImages.json";

// Generated by scripts/build-product-images.js — maps each product id to its
// de-duplicated gallery image paths (cover first).
const IMAGE_MANIFEST = productImages as Record<string, string[]>;

interface ProductSeed {
  id: string;
  imageCount: number;
  name: string;
  topCategory?: string;
  category: string;
  subcategory?: string;
  price: number;
  originalPrice?: number;
  stock: number;
  rating: number;
  reviewCount: number;
  shortDescription: string;
  description: string;
  features: string[];
  materials: string;
  care: string;
  dimensions?: string;
  tags?: string[];
  isNew?: boolean;
  isBestSeller?: boolean;
  isFeatured?: boolean;
}

const standardCare =
  "Sıcak suda yumuşak deterjanla elde yıkayın. Aşındırıcı süngerlerden ve bulaşık makinesinden uzak tutun. Tamamen kuruladıktan sonra kaldırın.";

const containerCare =
  "Sıcak sabunlu suda elde yıkayın, kapakları ayrı kurulayın. Bulaşık makinesinde üst raf önerilir; mikrodalga için lastik conta çıkarılmalıdır.";

const metalCare =
  "Kullanım sonrası nemli bezle silin. Paslanma riskine karşı her seferinde kurulayın. Klorlu temizleyicilerden kaçının.";

const woodCare =
  "Ahşap kapakları suya batırmayın; nemli bezle silin. Gövde elde yıkanır. Ahşap zaman zaman doğal yağ ile beslenmelidir.";

const seeds: ProductSeed[] = [
  // ── Doğrayıcılar & Rendeler ────────────────────────────────────────
  {
    id: "dor-m1",
    imageCount: 5,
    name: "Dora Manuel El Rondosu",
    category: "dograyicilar-rendeler",
    subcategory: "el-rondolari",
    price: 449.99,
    stock: 24,
    rating: 4.8,
    reviewCount: 312,
    shortDescription:
      "Üç bıçaklı sistemiyle saniyeler içinde sebze ve baharatlarınızı doğrar.",
    description:
      "Dora El Rondosu, ergonomik tutamağı ve paslanmaz çelik üçlü bıçak sistemiyle ön hazırlık sürenizi yarıya indirir. Tek elle çalıştırma kolaylığı, geniş hazne ve kaymaz tabanı sayesinde profesyonel sonuçlar sunar.",
    features: [
      "3'lü paslanmaz çelik bıçak sistemi",
      "500 ml şeffaf hazne",
      "Kaymaz silikon taban",
      "Tek elle pratik çalıştırma",
      "Bulaşık makinesinde yıkanabilir parçalar",
    ],
    materials: "Gıdayla temasa uygun ABS gövde, paslanmaz çelik bıçak, silikon taban.",
    care: standardCare,
    dimensions: "12 × 12 × 22 cm",
    tags: ["dograyici", "rondo", "el-aleti"],
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "dor-m2",
    imageCount: 5,
    name: "3 Bıçaklı Manuel Doğrayıcı",
    category: "dograyicilar-rendeler",
    subcategory: "manuel-dograyicilar",
    price: 299.99,
    stock: 18,
    rating: 4.6,
    reviewCount: 187,
    shortDescription:
      "Sebzelerden cevize, üç farklı bıçakla çok amaçlı doğrayıcı.",
    description:
      "3 Bıçaklı Manuel Doğrayıcı, değiştirilebilir bıçak setiyle ince doğrama, jülyen ve püre haline getirme işlerini tek üründe sunar. Şeffaf haznesi ve dökme kapağıyla mutfakta ekstra alan kaplamaz.",
    features: [
      "3 farklı doğrama bıçağı",
      "Şeffaf 800 ml hazne",
      "Geniş dökme ağızlı kapak",
      "Bulaşık makinesinde yıkanabilir",
      "Kompakt saklama tasarımı",
    ],
    materials: "Yüksek darbeye dayanıklı kompozit plastik, 304 paslanmaz çelik bıçak.",
    care: standardCare,
    dimensions: "16 × 16 × 18 cm",
    tags: ["3-bicak", "manuel", "dograyici"],
  },
  {
    id: "dor-m11",
    imageCount: 5,
    name: "Vera İpli Manuel Doğrayıcı",
    category: "dograyicilar-rendeler",
    subcategory: "ipli-dograyicilar",
    price: 299.99,
    stock: 41,
    rating: 4.7,
    reviewCount: 268,
    shortDescription:
      "İpli mekanizma sayesinde elektriksiz hızlı doğrama deneyimi.",
    description:
      "Vera ipli doğrayıcı, ipini çekerek bıçakları döndüren akıllı mekanizmasıyla soğan, sarımsak ve maydanozu birkaç hareketle inceltir. Şeffaf hazne kontrolü kolaylaştırır, kaymaz halka tezgâhta sabit kalmasını sağlar.",
    features: [
      "Çekme ipli bıçak mekanizması",
      "650 ml geniş hazne",
      "Kapak üzerinde bıçak güvenlik kilidi",
      "Sebze, meyve ve sert baharatlara uygun",
      "Şarja ihtiyaç duymaz",
    ],
    materials: "BPA içermeyen plastik gövde, paslanmaz çelik bıçak.",
    care: standardCare,
    dimensions: "15 × 15 × 14 cm",
    tags: ["ipli", "manuel", "dograyici"],
    isFeatured: true,
  },
  {
    id: "rnd-m9",
    imageCount: 5,
    name: "Profesyonel Mandolin Dilimleyici",
    category: "dograyicilar-rendeler",
    subcategory: "mandolin-dilimleyiciler",
    price: 349.99,
    stock: 9,
    rating: 4.8,
    reviewCount: 372,
    shortDescription:
      "Ayarlanabilir kalınlık ve toplama haznesiyle restoran kalitesinde dilimler.",
    description:
      "Profesyonel Mandolin Dilimleyici, 1–7 mm arasında kalınlık ayarı, dört farklı bıçak başlığı ve güvenli el koruyucusuyla sebzelerinizi eşit dilimler. Şeffaf toplama haznesi mutfak tezgâhınızı temiz tutar.",
    features: [
      "Ayarlanabilir 1–7 mm kalınlık",
      "4 farklı paslanmaz çelik bıçak",
      "Kayma önleyici taban",
      "Şeffaf 1,5 L toplama haznesi",
      "Güvenli el koruyucu aparat",
    ],
    materials: "Paslanmaz çelik bıçaklar, ABS gövde, silikon kaymaz taban.",
    care: metalCare,
    dimensions: "38 × 14 × 12 cm",
    tags: ["mandolin", "dilimleyici", "profesyonel"],
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "rnd-m12",
    imageCount: 5,
    name: "Flat Ayarlanabilir Mandolin",
    category: "dograyicilar-rendeler",
    subcategory: "mandolin-dilimleyiciler",
    price: 219.99,
    stock: 27,
    rating: 4.5,
    reviewCount: 154,
    shortDescription:
      "Düz tasarımı sayesinde çekmecede minimum yer kaplar.",
    description:
      "Flat Ayarlanabilir Mandolin, kompakt yapısı ve hızlı kalınlık değiştirme düğmesiyle günlük kullanım için idealdir. Üç bıçak modu sayesinde dilim, çubuk ve jülyen kesimleri yapabilirsiniz.",
    features: [
      "Üç farklı kesim modu",
      "Tek dokunuşla kalınlık ayarı",
      "Kompakt, ince gövde",
      "Bulaşık makinesinde yıkanabilir",
    ],
    materials: "Paslanmaz çelik bıçak, ABS gövde.",
    care: standardCare,
    dimensions: "36 × 12 × 4 cm",
    tags: ["mandolin", "ince-tasarim"],
  },
  {
    id: "rnd-m10",
    imageCount: 5,
    name: "Çok Yönlü Rende Seti",
    category: "dograyicilar-rendeler",
    subcategory: "cok-yonlu-rendeler",
    price: 249.99,
    stock: 33,
    rating: 4.6,
    reviewCount: 203,
    shortDescription: "Dört farklı rende yüzeyi tek üründe.",
    description:
      "Çok Yönlü Rende Seti; ince, kalın, çubuk ve dilim olmak üzere dört farklı yüzey sunar. Ergonomik tutamağı ve kaymaz tabanıyla güvenli kullanım sağlar.",
    features: [
      "4 farklı paslanmaz çelik yüzey",
      "Ergonomik kavrama",
      "Kaymaz silikon taban",
      "Asma deliği ile pratik saklama",
    ],
    materials: "Paslanmaz çelik gövde, TPR tutamak.",
    care: metalCare,
    dimensions: "28 × 12 × 8 cm",
    tags: ["rende", "set", "cok-yonlu"],
  },
  {
    id: "rnd-rev",
    imageCount: 5,
    name: "Profesyonel Multi Rende & Dilimleyici",
    category: "dograyicilar-rendeler",
    subcategory: "profesyonel-setler",
    price: 139.99,
    stock: 7,
    rating: 4.9,
    reviewCount: 289,
    shortDescription:
      "Beş bıçaklı profesyonel set, restoran kalitesinde sonuç.",
    description:
      "Profesyonel Multi Rende & Dilimleyici, beş değiştirilebilir bıçak başlığıyla restoran kalitesinde kesim sunar. Saklama haznesi, el koruyucu ve kaymaz taban dahildir.",
    features: [
      "5 değiştirilebilir bıçak",
      "Geniş 2 L toplama haznesi",
      "Güvenlik el koruyucu",
      "Bıçak saklama kutusu",
      "Tek tuşla kalınlık ayarı",
    ],
    materials: "Paslanmaz çelik, ABS, silikon.",
    care: metalCare,
    dimensions: "42 × 18 × 18 cm",
    tags: ["profesyonel", "set", "mandolin"],
    isFeatured: true,
    isBestSeller: true,
  },

  // ── Saklama Kapları ──────────────────────────────────────────────
  {
    id: "skl-esk0001",
    imageCount: 5,
    name: "Uzun Boy Vakumlu Saklama Kavanozu",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 399.99,
    stock: 47,
    rating: 4.7,
    reviewCount: 198,
    shortDescription: "Spagetti, makarna ve uzun gıdalarınız için yüksek boy kavanoz.",
    description:
      "Uzun Boy Vakumlu Saklama Kavanozu, dar tabanlı uzun gövdesiyle makarna, spagetti ve uzun gıdaları eksiksiz saklamanıza imkân verir. Vakum kilidi tazeliği korur.",
    features: [
      "Uzun ince gövde",
      "Vakum kilitli kapak",
      "BPA içermez",
      "Şeffaf gövde içerik kontrolü",
    ],
    materials: "BPA içermeyen kompozit gövde, silikon conta.",
    care: containerCare,
    dimensions: "10 × 10 × 28 cm · 1.5 L",
    tags: ["uzun", "vakumlu", "kavanoz"],
  },
  {
    id: "skl-esk0002",
    imageCount: 5,
    name: "Bonny Vakumlu Saklama Kavanozu 0.6L",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 799.99,
    stock: 124,
    rating: 4.6,
    reviewCount: 384,
    shortDescription:
      "Küçük boy vakumlu kavanoz; baharat ve kuruyemiş için ideal.",
    description:
      "Bonny serisinin küçük boyu, baharat dolaplarınızda tasarrufla yer tutar. Vakum mekanizması ve istiflenebilir yapı küçük gıdalarınızı korur.",
    features: [
      "Tek dokunuş vakum kapağı",
      "Modüler istiflenebilir tasarım",
      "BPA içermez",
      "Şeffaf gövde",
    ],
    materials: "Saydam plastik, silikon conta.",
    care: containerCare,
    dimensions: "10 × 10 × 12 cm · 0.6 L",
    tags: ["vakumlu", "kavanoz"],
  },
  {
    id: "skl-esk0003",
    imageCount: 5,
    name: "Bonny Vakumlu Saklama Kavanozu 0.9L",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 1599.99,
    stock: 86,
    rating: 4.7,
    reviewCount: 512,
    shortDescription:
      "Orta boy vakumlu saklama kavanozu kuru gıdalarınızı uzun süre taze tutar.",
    description:
      "Bonny Vakumlu Saklama Kavanozu, tek dokunuşla kapanan vakum kilidiyle baharat, çay, kahve ve kuru gıdaları aylarca taze tutar. Modüler tasarımı kavanozları üst üste istiflemenize olanak verir.",
    features: [
      "Tek dokunuş vakum kilidi",
      "Modüler istiflenebilir gövde",
      "BPA içermez",
      "Bulaşık makinesinde yıkanabilir gövde",
      "Şeffaf gövde ile içerik kontrolü",
    ],
    materials: "Tritan™ benzeri saydam plastik, silikon conta.",
    care: containerCare,
    dimensions: "10 × 10 × 16 cm · 0.9 L",
    tags: ["vakumlu", "kavanoz", "saklama"],
    isBestSeller: true,
  },
  {
    id: "skl-esk0101",
    imageCount: 3,
    name: "Luxe Premium Vakumlu Kavanoz – Gold",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 279,
    originalPrice: 329,
    stock: 64,
    rating: 4.8,
    reviewCount: 428,
    shortDescription: "Saten dokulu premium gövde, mat altın detaylı kapak.",
    description:
      "Luxe Premium serisi, saten dokulu gövdesi ve mat metalik kapağıyla mutfak tezgâhlarında dekoratif duruşa sahip. Vakum sistemi sayesinde içerikleri uzun süre korur.",
    features: [
      "Saten dokulu cam görünümlü gövde",
      "Metalik mat vakum kapağı",
      "İstiflenebilir tasarım",
      "Şeffaf gövde içerik kontrolü",
    ],
    materials: "BPA içermeyen kompozit, mat metalik kaplama.",
    care: containerCare,
    dimensions: "10 × 10 × 16 cm · 1 L",
    tags: ["premium", "vakumlu", "gold"],
    isNew: true,
    isFeatured: true,
  },
  {
    id: "skl-esk0102",
    imageCount: 3,
    name: "Luxe Premium Vakumlu Kavanoz – Gümüş",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 279,
    stock: 49,
    rating: 4.8,
    reviewCount: 263,
    shortDescription: "Saten dokulu gövde, mat gümüş tonlu kapak.",
    description:
      "Luxe Premium serisinin gümüş versiyonu, mutfağınıza dengeli bir nötr ton katar. Vakum sistemi sayesinde içeriği korur.",
    features: [
      "Saten dokulu gövde",
      "Mat gümüş vakum kapağı",
      "İstiflenebilir tasarım",
    ],
    materials: "BPA içermeyen kompozit gövde.",
    care: containerCare,
    dimensions: "10 × 10 × 16 cm · 1 L",
    tags: ["premium", "vakumlu", "gumus"],
    isNew: true,
  },
  {
    id: "skl-esk0103",
    imageCount: 3,
    name: "Luxe Premium Vakumlu Kavanoz – Roze",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 279,
    stock: 38,
    rating: 4.7,
    reviewCount: 184,
    shortDescription: "Saten dokulu gövde, modern roze altın kapak.",
    description:
      "Luxe Premium serisinin roze versiyonu, sıcak ve modern bir doku katar. Tezgâhlarda dekoratif şıklık sağlar.",
    features: [
      "Saten dokulu gövde",
      "Roze altın metalik vakum kapağı",
      "İstiflenebilir tasarım",
    ],
    materials: "BPA içermeyen kompozit gövde.",
    care: containerCare,
    dimensions: "10 × 10 × 16 cm · 1 L",
    tags: ["premium", "vakumlu", "roze"],
    isNew: true,
  },
  {
    id: "skl-esk0211",
    imageCount: 4,
    name: "Woody Ahşap Kapaklı Kavanoz 0.9L",
    category: "saklama-kaplari",
    subcategory: "ahsap-kapakli",
    price: 199,
    stock: 92,
    rating: 4.7,
    reviewCount: 198,
    shortDescription: "Doğal ahşap kapaklı kavanoz, sıcak Scandi dokunuşu.",
    description:
      "Woody Ahşap Kapaklı Kavanoz, doğal kayın ağacı kapağı ve silikon contası sayesinde hem dekoratif hem de işlevseldir. Açık raflarda sergilemek için idealdir.",
    features: [
      "Doğal kayın ağacı kapak",
      "Silikon hava sızdırmaz conta",
      "Cam görünümlü şeffaf gövde",
      "Açık rafta sergi uyumu",
    ],
    materials: "Cam görünümlü kompozit, kayın ağacı kapak.",
    care: woodCare,
    dimensions: "10 × 10 × 14 cm · 0.9 L",
    tags: ["ahsap", "scandi", "kavanoz"],
  },
  {
    id: "skl-esk0212",
    imageCount: 5,
    name: "Woody Ahşap Kapaklı Kavanoz 1.4L",
    category: "saklama-kaplari",
    subcategory: "ahsap-kapakli",
    price: 249,
    originalPrice: 299,
    stock: 71,
    rating: 4.7,
    reviewCount: 165,
    shortDescription:
      "Geniş hacimli ahşap kapaklı kavanoz; tahıllar için ideal.",
    description:
      "Woody serisinin geniş hacimli boyu, kahvaltılık gevrek ve tahıllarınız için modern bir görünüm sunar.",
    features: [
      "Doğal ahşap kapak",
      "Geniş ağız",
      "Şeffaf cam görünüm",
    ],
    materials: "Cam görünümlü kompozit, ahşap kapak.",
    care: woodCare,
    dimensions: "12 × 12 × 20 cm · 1.4 L",
    tags: ["ahsap", "scandi", "kavanoz"],
  },
  {
    id: "skl-esk0213",
    imageCount: 4,
    name: "Woody Ahşap Kapaklı Kavanoz Mini",
    category: "saklama-kaplari",
    subcategory: "ahsap-kapakli",
    price: 159,
    stock: 108,
    rating: 4.6,
    reviewCount: 121,
    shortDescription:
      "Küçük boy ahşap kapaklı kavanoz; baharat ve atıştırmalık için.",
    description:
      "Woody serisinin küçük boyu, baharatlık olarak ya da atıştırmalıkları sergilemek için ideal şıklıkta bir tercihtir.",
    features: [
      "Doğal kayın ağacı kapak",
      "Silikon conta",
      "Küçük boy zarif gövde",
    ],
    materials: "Cam görünümlü kompozit, ahşap kapak.",
    care: woodCare,
    dimensions: "9 × 9 × 11 cm · 0.5 L",
    tags: ["ahsap", "mini", "kavanoz"],
  },
  {
    id: "skl-esk1001",
    imageCount: 5,
    name: "Kare Vakumlu Saklama Seti 3'lü",
    category: "saklama-kaplari",
    subcategory: "saklama-setleri",
    price: 749,
    originalPrice: 899,
    stock: 22,
    rating: 4.9,
    reviewCount: 318,
    shortDescription: "Üç farklı boyda hava sızdırmaz kare set.",
    description:
      "Kare Saklama Seti, üç farklı boyutu sayesinde mutfak dolabınızda eksiksiz bir saklama çözümü sunar. Aynı tabana sahip kapları üst üste istiflemek mümkün.",
    features: [
      "0.6 L + 1.2 L + 2.0 L",
      "Dört kelebek kilit",
      "İstiflenebilir kare gövde",
      "BPA içermez",
    ],
    materials: "Gıda sınıfı PP, silikon.",
    care: containerCare,
    dimensions: "Set kutusu: 22 × 22 × 20 cm",
    tags: ["set", "saklama", "kare"],
    isBestSeller: true,
  },
  {
    id: "skl-esk1101",
    imageCount: 3,
    name: "Crystal Şeffaf Hava Sızdırmaz Kap",
    category: "saklama-kaplari",
    subcategory: "cam-gorunumlu",
    price: 189,
    stock: 58,
    rating: 4.5,
    reviewCount: 142,
    shortDescription: "Cam görünümlü, kelebek kilitli pratik saklama kabı.",
    description:
      "Crystal serisi, cam görünümlü gövdesi ve dört taraftan kilitli kapağıyla hava sızdırmaz saklama sunar. Hafiftir, kırılmaz ve buzdolabında yer kazandırır.",
    features: [
      "Dört kelebek kilit",
      "Hava sızdırmaz silikon conta",
      "Buzdolabında istiflenebilir",
      "Mikrodalga uyumlu (kapak hariç)",
    ],
    materials: "BPA içermeyen PP, silikon conta.",
    care: containerCare,
    dimensions: "18 × 13 × 8 cm · 1 L",
    tags: ["cam-gorunum", "hava-sizdirmaz"],
  },
  {
    id: "skl-esk1211",
    imageCount: 5,
    name: "Tall Cam Görünümlü Vakumlu Kavanoz",
    category: "saklama-kaplari",
    subcategory: "vakumlu-kavanozlar",
    price: 269,
    stock: 47,
    rating: 4.7,
    reviewCount: 138,
    shortDescription: "Uzun boylu, dar tabanlı kavanoz; uzun gıdalar için.",
    description:
      "Tall serisinin uzun gövdesi, spagetti, makarna ve uzun ürünleri eksiksiz saklamanıza imkân verir. Vakum kilidi tazeliği korur.",
    features: ["Uzun gövde", "Vakum kapağı", "Şeffaf görünüm"],
    materials: "BPA içermeyen plastik, silikon conta.",
    care: containerCare,
    dimensions: "10 × 10 × 28 cm · 1.5 L",
    tags: ["uzun", "vakumlu"],
  },
  {
    id: "skl-m5",
    imageCount: 5,
    name: "Modüler Kapaklı Saklama Kabı 0.9L",
    category: "saklama-kaplari",
    subcategory: "dikdortgen-kaplar",
    price: 53.13,
    stock: 134,
    rating: 4.6,
    reviewCount: 221,
    shortDescription: "Siyah kapaklı, buzdolabına ergonomik sığan dikdörtgen kap.",
    description:
      "Modüler Saklama Kabı, dolap ölçülerine göre tasarlanmış formuyla yerden kazandırır. Şık siyah kapak detayı ve hava sızdırmaz contası ile yemekleri taze tutar.",
    features: [
      "Hava sızdırmaz kapak",
      "Buzdolabı dostu form",
      "Mikrodalga uyumlu",
      "İstiflenebilir",
    ],
    materials: "BPA içermeyen PP, silikon conta.",
    care: containerCare,
    dimensions: "18 × 14 × 7 cm · 0.9 L",
    tags: ["dikdortgen", "siyah-kapak"],
  },
  {
    id: "skl-m6",
    imageCount: 5,
    name: "Dikdörtgen Saklama Kabı Orta",
    category: "saklama-kaplari",
    subcategory: "dikdortgen-kaplar",
    price: 95.63,
    stock: 102,
    rating: 4.6,
    reviewCount: 174,
    shortDescription: "Orta boy dikdörtgen kap; günlük yemekler için.",
    description:
      "Aynı seriyle istiflenebilen orta boy dikdörtgen kap, günlük yemeklerinizi taze tutarken buzdolabınızda düzen sağlar.",
    features: [
      "1.2 L hacim",
      "Hava sızdırmaz kilit",
      "Mikrodalga uyumlu",
    ],
    materials: "PP gövde, silikon conta.",
    care: containerCare,
    dimensions: "20 × 14 × 8 cm · 1.2 L",
    tags: ["dikdortgen", "orta"],
  },
  {
    id: "skl-m7",
    imageCount: 5,
    name: "Dikdörtgen Saklama Kabı Büyük",
    category: "saklama-kaplari",
    subcategory: "dikdortgen-kaplar",
    price: 151.8,
    stock: 89,
    rating: 4.6,
    reviewCount: 152,
    shortDescription: "Geniş hacimli dikdörtgen kap; sebzeler ve hazır yemekler için.",
    description:
      "Geniş hacmiyle önceden hazırlanan yemekler ve sebzeler için ideal. Aynı seri tasarım bütünlüğü sunar.",
    features: ["1.8 L geniş hacim", "Hava sızdırmaz kilit", "Mikrodalga uyumlu"],
    materials: "PP gövde, silikon conta.",
    care: containerCare,
    dimensions: "24 × 16 × 8 cm · 1.8 L",
    tags: ["dikdortgen", "geniş"],
  },
  {
    id: "skl-m8",
    imageCount: 3,
    name: "3'lü Saklama Kabı Seti",
    category: "saklama-kaplari",
    subcategory: "saklama-setleri",
    price: 349.99,
    stock: 35,
    rating: 4.8,
    reviewCount: 247,
    shortDescription:
      "Aynı seriyle uyumlu üç boy saklama kabı seti.",
    description:
      "3'lü Saklama Kabı Seti, küçük, orta ve büyük boyutuyla buzdolabı için eksiksiz çözüm sunar. Modüler istif tasarımı yer kazandırır.",
    features: ["0.9 L + 1.2 L + 1.8 L", "Modüler istif", "Hava sızdırmaz kilit"],
    materials: "PP gövde, silikon conta.",
    care: containerCare,
    dimensions: "Set: 24 × 16 × 20 cm",
    tags: ["set", "saklama"],
    isFeatured: true,
  },

  // ── Servis & Sofra ────────────────────────────────────────────────
  {
    id: "srv-kal0001",
    imageCount: 5,
    name: "Klasik Salata Kasesi Büyük",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 36.43,
    stock: 38,
    rating: 4.7,
    reviewCount: 156,
    shortDescription: "Geniş ağız ve derin formuyla servis dostu salata kasesi.",
    description:
      "Klasik Salata Kasesi, geniş ağız ve derin formuyla salata, makarna ve meyveleri sergilemek için tasarlandı. Mat parlak yüzeyi sofraya zarif bir hat katar.",
    features: ["3 L geniş hacim", "Mat parlak yüzey", "Bulaşık makinesi uyumlu"],
    materials: "Yüksek dirençli stoneware seramik.",
    care: standardCare,
    dimensions: "Ø 28 × 12 cm",
    tags: ["salata", "kase", "buyuk"],
    isFeatured: true,
  },
  {
    id: "srv-kal0002",
    imageCount: 5,
    name: "Klasik Salata Kasesi Orta",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 68.31,
    stock: 64,
    rating: 4.6,
    reviewCount: 121,
    shortDescription: "Orta boy klasik kase; günlük servisler için ideal.",
    description:
      "Klasik kasenin orta boyu, günlük servislerinizi şıklaştırır. Set olarak diğer boylarla uyumlu kullanılabilir.",
    features: ["2 L hacim", "Aynı seri tasarım uyumu", "Mat parlak yüzey"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "Ø 24 × 10 cm",
    tags: ["salata", "kase"],
  },
  {
    id: "srv-kal0003",
    imageCount: 5,
    name: "Klasik Çerez Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 88.04,
    stock: 132,
    rating: 4.5,
    reviewCount: 78,
    shortDescription:
      "Küçük boy çerez kasesi; mezeler ve atıştırmalıklar için.",
    description:
      "Küçük boy klasik kase, mezeler ve atıştırmalıklar için zarif bir sunum sunar. Aynı seri ile kombinlenebilir.",
    features: ["0.6 L hacim", "Aynı seri uyumu", "Mat parlak yüzey"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "Ø 14 × 7 cm",
    tags: ["cerez", "kase", "kucuk"],
  },
  {
    id: "srv-kal1001",
    imageCount: 5,
    name: "Kapaklı Servis Kasesi Büyük",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 66.79,
    stock: 26,
    rating: 4.8,
    reviewCount: 193,
    shortDescription: "Sızdırmaz kapaklı büyük boy servis ve saklama kasesi.",
    description:
      "Kapaklı Servis Kasesi, sızdırmaz şeffaf kapağı sayesinde hazırladığınız salata ve yemekleri sofradan buzdolabına taşımanızı sağlar. Büyük boyu kalabalık sofralar için idealdir.",
    features: ["Sızdırmaz şeffaf kapak", "3 L hacim", "Buzdolabı & saklama dostu", "Bulaşık makinesi uyumlu"],
    materials: "BPA içermeyen, gıdaya uygun plastik.",
    care: containerCare,
    dimensions: "Ø 28 × 12 cm",
    tags: ["kapakli", "kase", "buyuk"],
    isBestSeller: true,
  },
  {
    id: "srv-kal1002",
    imageCount: 5,
    name: "Kapaklı Servis Kasesi Orta",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 116.89,
    stock: 51,
    rating: 4.7,
    reviewCount: 162,
    shortDescription: "Aynı seriden orta boy kapaklı kase.",
    description:
      "Kapaklı serinin orta boyu, sızdırmaz kapağıyla salataları ve yemekleri tazece saklar.",
    features: ["Sızdırmaz şeffaf kapak", "2 L hacim", "Buzdolabı dostu"],
    materials: "BPA içermeyen, gıdaya uygun plastik.",
    care: containerCare,
    dimensions: "Ø 24 × 10 cm",
    tags: ["kapakli", "kase"],
  },
  {
    id: "srv-kal1003",
    imageCount: 5,
    name: "Kapaklı Servis Kasesi Küçük",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 156.35,
    stock: 89,
    rating: 4.6,
    reviewCount: 84,
    shortDescription:
      "Aperatif ve sos için kapaklı küçük kase.",
    description:
      "Küçük boy kapaklı kase, aperatif ve sosları kapağıyla birlikte pratikçe saklamanızı sağlar.",
    features: ["Sızdırmaz şeffaf kapak", "0.6 L hacim", "Buzdolabı dostu"],
    materials: "BPA içermeyen, gıdaya uygun plastik.",
    care: containerCare,
    dimensions: "Ø 14 × 7 cm",
    tags: ["kapakli", "kucuk"],
  },
  {
    id: "srv-kas0001",
    imageCount: 5,
    name: "Klasik XXL Salata Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 91.08,
    stock: 22,
    rating: 4.8,
    reviewCount: 142,
    shortDescription: "Davet sofraları için ekstra büyük klasik kase.",
    description:
      "Klasik serinin XXL boyu, kalabalık sofralar için tasarlandı. Geniş ağzı ile sunum dostudur.",
    features: ["4.5 L hacim", "Mat parlak yüzey", "Bulaşık makinesi uyumlu"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "Ø 32 × 14 cm",
    tags: ["xxl", "davet", "kase"],
  },
  {
    id: "srv-kas1001",
    imageCount: 5,
    name: "Dokulu XXL Servis Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 159.39,
    stock: 16,
    rating: 4.9,
    reviewCount: 211,
    shortDescription: "Davet sofralarına özel ekstra büyük dokulu kase.",
    description:
      "Dokulu seriden XXL kase, kalabalık davet sofraları için tasarlandı. Geniş ağzı ile sunum dostudur.",
    features: ["4.5 L hacim", "Dokulu zarif yüzey", "Bulaşık makinesi uyumlu"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "Ø 32 × 14 cm",
    tags: ["xxl", "davet", "dokulu"],
    isFeatured: true,
  },
  {
    id: "srv-kau0001",
    imageCount: 5,
    name: "Klasik Dikdörtgen Servis Tabağı",
    category: "servis-sofra",
    subcategory: "servis-tabaklari",
    price: 72.86,
    stock: 73,
    rating: 4.5,
    reviewCount: 96,
    shortDescription:
      "Dikdörtgen servis tabağı; mezeler ve kahvaltılar için.",
    description:
      "Klasik Dikdörtgen Servis Tabağı, geniş kullanım yüzeyiyle kahvaltı ve meze servisleri için pratik bir çözümdür.",
    features: ["Geniş 32 × 18 cm yüzey", "Mat parlak ton"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "32 × 18 × 3 cm",
    tags: ["dikdortgen", "servis"],
  },
  {
    id: "srv-kau1001",
    imageCount: 5,
    name: "Kapaklı Servis Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 121.44,
    stock: 42,
    rating: 4.7,
    reviewCount: 128,
    shortDescription: "Sızdırmaz kapaklı geniş servis kasesi.",
    description:
      "Kapaklı Servis Kasesi; sızdırmaz şeffaf kapağıyla salataları, mezeleri ve yemekleri sofrada sunmanızı, ardından buzdolabında saklamanızı sağlar.",
    features: ["Sızdırmaz şeffaf kapak", "Geniş hacim", "Buzdolabı & saklama dostu", "Bulaşık makinesi uyumlu"],
    materials: "BPA içermeyen, gıdaya uygun plastik.",
    care: containerCare,
    dimensions: "Ø 26 × 11 cm",
    tags: ["kapakli", "kase", "servis"],
  },
  {
    id: "srv-kav0001",
    imageCount: 5,
    name: "Klasik Oval Servis Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 37.95,
    stock: 31,
    rating: 4.6,
    reviewCount: 105,
    shortDescription: "Salata ve sıcak servisler için oval form.",
    description:
      "Klasik Oval Servis Kasesi, dengeli oval formuyla salatalar ve sıcak servisler için zarif görünüm sunar.",
    features: ["2.4 L hacim", "Oval form"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "30 × 20 × 9 cm",
    tags: ["oval", "kase"],
  },
  {
    id: "srv-kav1001",
    imageCount: 5,
    name: "Dokulu Oval Servis Kasesi",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 68.31,
    stock: 19,
    rating: 4.8,
    reviewCount: 154,
    shortDescription: "Dokulu yüzeyli oval servis kasesi.",
    description:
      "Dokulu Oval Kase, salataları ve ana yemekleri zarif bir oval form ile servis etmenizi sağlar.",
    features: ["El yapımı doku", "2.4 L hacim", "Mat doğal ton"],
    materials: "Stoneware seramik.",
    care: standardCare,
    dimensions: "30 × 20 × 9 cm",
    tags: ["dokulu", "oval"],
  },
  {
    id: "aks-kag",
    imageCount: 12,
    name: "Desenli Kapaklı Kase Seti (3'lü İç İçe)",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 339.99,
    stock: 64,
    rating: 4.5,
    reviewCount: 154,
    shortDescription:
      "İç içe geçen üç boy desenli kase; sızdırmaz kapaklarıyla hem servis hem saklama.",
    description:
      "Desenli Kapaklı Kase Seti; küçük, orta ve büyük olmak üzere iç içe geçen üç kaseden oluşur. Yiv desenli mat gövdesi sofrada şık dururken, sızdırmaz şeffaf kapakları artan yemekleri doğrudan buzdolabında saklamanıza imkân verir. İç içe geçen yapısı dolapta az yer kaplar; mint, vizon, beyaz ve siyah renk seçenekleriyle mutfağınıza uyum sağlar.",
    features: [
      "İç içe geçen 3 boy: küçük, orta, büyük",
      "Sızdırmaz şeffaf servis & saklama kapakları",
      "Dekoratif yiv desenli mat gövde",
      "Sofrada servise ve buzdolabında saklamaya uygun",
      "Bulaşık makinesinde yıkanabilir",
    ],
    materials: "BPA içermeyen, gıdaya uygun plastik gövde; şeffaf saklama kapağı.",
    care: containerCare,
    dimensions: "Küçük Ø19 · Orta Ø23 · Büyük Ø27 cm (iç içe geçer)",
    tags: ["kase", "kase-seti", "ic-ice", "desenli", "kapakli", "servis", "saklama", "salata"],
  },
  {
    id: "srv-sua",
    imageCount: 5,
    name: "Süzgeç",
    category: "servis-sofra",
    subcategory: "salata-kurutucular",
    price: 79.99,
    stock: 88,
    rating: 4.7,
    reviewCount: 219,
    shortDescription:
      "Sebze, meyve ve makarnayı pratikçe süzen geniş süzgeç.",
    description:
      "Geniş süzgeç, sık delikli gövdesi ve yan tutamaklarıyla sebze, meyve ve makarnayı hızlıca durulayıp süzmenizi sağlar. Dengeli tabanı lavaboda sabit durur.",
    features: ["Sık delikli gövde", "Yandan tutamaklı", "Dengeli taban", "Bulaşık makinesi uyumlu"],
    materials: "BPA içermeyen, gıdaya uygun plastik.",
    care: containerCare,
    dimensions: "Ø 26 × 12 cm",
    tags: ["suzgec", "kevgir", "yikama"],
    isBestSeller: true,
  },
  {
    id: "srv-suh",
    imageCount: 5,
    name: "Ergonomik İçecek Sürahisi",
    category: "servis-sofra",
    subcategory: "surahi-karaf",
    price: 159.99,
    stock: 67,
    rating: 4.5,
    reviewCount: 137,
    shortDescription:
      "Tek elle kullanım için ergonomik kulplu sürahi.",
    description:
      "Ergonomik İçecek Sürahisi, kulp tasarımı ve dengeli ağırlığıyla kalabalık davetlerde rahat servis sunar.",
    features: ["Ergonomik kulp", "2.2 L hacim", "Cam görünümlü gövde"],
    materials: "Saydam kompozit plastik.",
    care: containerCare,
    dimensions: "14 × 12 × 26 cm · 2.2 L",
    tags: ["surahi", "ergonomik"],
  },

  // ── Mutfak Yardımcıları ──────────────────────────────────────────
  {
    id: "alt-kmn",
    imageCount: 12,
    name: "Esnek Kesme Tahtası",
    category: "mutfak-yardimcilari",
    subcategory: "kesme-tahtalari",
    price: 249.99,
    stock: 21,
    rating: 4.9,
    reviewCount: 487,
    shortDescription:
      "Bükülebilir gövdesiyle doğradıklarınızı tek harekette tencereye aktaran esnek kesme tahtası.",
    description:
      "Esnek Kesme Tahtası, ince ve bükülebilir gövdesi sayesinde doğradığınız sebze ve meyveleri kıvırıp doğrudan tencere ya da kaseye dökmenizi sağlar. Mat yüzeyi bıçağı yormaz ve tezgâhınızı korur; kenarındaki asma deliğiyle kolayca saklanır.",
    features: [
      "Bükülebilir, esnek ince gövde",
      "Doğradıklarını kolayca dökme kolaylığı",
      "Bıçağı yormayan yumuşak yüzey",
      "Asma delikli pratik saklama",
      "Bulaşık makinesinde yıkanabilir",
    ],
    materials: "Gıdaya uygun, BPA içermeyen esnek polipropilen.",
    care:
      "Kullanım sonrası sıcak sabunlu suda yıkayın; bulaşık makinesinde üst rafta yıkanabilir. Kesme sonrası iyice kurulayın.",
    dimensions: "Yaklaşık 37 × 29 cm",
    tags: ["kesme-tahtasi", "esnek", "dograma"],
  },
  {
    id: "alt-kpg",
    imageCount: 12,
    name: "Kaymaz Tabanlı Kesme Tahtası",
    category: "mutfak-yardimcilari",
    subcategory: "kesme-tahtalari",
    price: 229.99,
    stock: 55,
    rating: 4.7,
    reviewCount: 198,
    shortDescription:
      "Kaymaz ayakları ve kenar oluğuyla tezgâhı temiz tutan dayanıklı kesme tahtası.",
    description:
      "Kaymaz Tabanlı Kesme Tahtası, alt köşelerindeki silikon ayaklar sayesinde doğrama sırasında kaymaz. Yükseltilmiş kenar oluğu ekmek kırıntılarını ve sebze sularını tezgâha taşırmadan toplar; geniş yüzeyi günlük doğramalar için idealdir.",
    features: [
      "Kaymaz silikon ayaklar",
      "Kırıntı ve su toplayan kenar oluğu",
      "Geniş, dayanıklı doğrama yüzeyi",
      "Çift taraflı kullanım",
      "Bulaşık makinesinde yıkanabilir",
    ],
    materials: "Gıdaya uygun, BPA içermeyen plastik gövde; kaymaz silikon ayaklar.",
    care:
      "Kullanım sonrası sıcak sabunlu suda yıkayın; bulaşık makinesinde üst rafta yıkanabilir. İyice kurulayın.",
    dimensions: "Yaklaşık 38 × 25 cm",
    tags: ["kesme-tahtasi", "kaymaz", "kenarli", "dograma"],
  },
  {
    id: "alt-m3",
    imageCount: 5,
    name: "Geniş Manuel Salata Kurutucu",
    category: "mutfak-yardimcilari",
    subcategory: "salata-kurutucular",
    price: 339.99,
    stock: 28,
    rating: 4.8,
    reviewCount: 271,
    shortDescription:
      "Geniş hazneli salata kurutucu; tek hareketle sebzelerinizi kurutur.",
    description:
      "Geniş Manuel Salata Kurutucu, 5 litrelik kapasitesi ve sağlam ip mekanizmasıyla kalabalık sofralarda hız sağlar. Santrifüj iç haznesi servis kasesi olarak da kullanılabilir.",
    features: [
      "5 L hazne",
      "İpli santrifüj mekanizma",
      "Servis kasesi uyumu",
      "Kaymaz taban",
    ],
    materials: "BPA içermeyen kompozit.",
    care: standardCare,
    dimensions: "Ø 26 × 18 cm",
    tags: ["salata", "kurutucu"],
    isFeatured: true,
  },
  {
    id: "soy-sol1",
    imageCount: 5,
    name: "Klasik Sebze Soyacağı",
    category: "mutfak-yardimcilari",
    subcategory: "soyacaklar",
    price: 49.99,
    stock: 142,
    rating: 4.6,
    reviewCount: 218,
    shortDescription:
      "Keskin paslanmaz çelik bıçaklı, ergonomik kavramalı sebze soyacağı.",
    description:
      "Klasik Sebze Soyacağı, dayanıklı paslanmaz çelik bıçağı ve kaymaz tutamağıyla günlük kullanım için pratik bir tercih. Patates, havuç ve elma için ideal.",
    features: [
      "Y formlu klasik tasarım",
      "Paslanmaz çelik bıçak",
      "Kaymaz silikon tutamak",
      "Bulaşık makinesinde yıkanabilir",
    ],
    materials: "Paslanmaz çelik bıçak, TPR tutamak.",
    care: metalCare,
    dimensions: "14 × 7 × 2 cm",
    tags: ["soyacak", "sebze", "klasik"],
  },
  {
    id: "soy-sol2",
    imageCount: 5,
    name: "Premium Çok Yönlü Soyacak",
    category: "mutfak-yardimcilari",
    subcategory: "soyacaklar",
    price: 49.99,
    stock: 96,
    rating: 4.7,
    reviewCount: 184,
    shortDescription:
      "Çift bıçaklı, jülyen kesim özellikli premium soyacak.",
    description:
      "Premium Çok Yönlü Soyacak, klasik soyma ve jülyen kesim bıçaklarını tek üründe sunar. Patates gözü çıkartma aparatı ile çok amaçlıdır.",
    features: [
      "Çift fonksiyonlu bıçak",
      "Jülyen kesim seçeneği",
      "Patates gözü temizleme aparatı",
      "Ergonomik premium tutamak",
    ],
    materials: "Paslanmaz çelik bıçak, ABS tutamak.",
    care: metalCare,
    dimensions: "14 × 7 × 2 cm",
    tags: ["soyacak", "premium", "julyen"],
    isNew: true,
  },
  {
    id: "aks-m4",
    imageCount: 5,
    name: "Silikon Buz Kalıbı Kapaklı",
    category: "mutfak-yardimcilari",
    subcategory: "buz-kaliplari",
    price: 60.72,
    stock: 198,
    rating: 4.6,
    reviewCount: 312,
    shortDescription:
      "Dökülmez kapaklı silikon buz kalıbı; eşit ve şeffaf buzlar.",
    description:
      "Silikon Buz Kalıbı, esnek silikon yapısı sayesinde buzları tek dokunuşla çıkarmanızı sağlar. Kapağı sayesinde diğer kokuları emmez ve istiflenebilir.",
    features: [
      "Esnek silikon yapı",
      "Hava sızdırmaz kapak",
      "Üst üste istiflenebilir",
      "21 buz kapasitesi",
    ],
    materials: "Gıda sınıfı silikon, BPA içermez kapak.",
    care: standardCare,
    dimensions: "22 × 12 × 4 cm",
    tags: ["buz", "silikon"],
  },

  // ── Eklenenler (Excel: ZEST HOME SATIŞ FİYATI) ───────────────────
  {
    id: "rnd-m1",
    imageCount: 12,
    name: "Star Kutu Rende",
    category: "dograyicilar-rendeler",
    subcategory: "cok-yonlu-rendeler",
    price: 99.99,
    stock: 60,
    rating: 4.7,
    reviewCount: 24,
    shortDescription:
      "Çok yüzeyli paslanmaz çelik kutu rende; peynirden sebzeye her iş tek üründe.",
    description:
      "Star Kutu Rende, farklı rende yüzeyleriyle peynir, sebze ve sert gıdaları kolayca işler. Geniş ergonomik tutamağı ve dengeli kutu tabanı güvenli kullanım sağlar; canlı renk seçeneğiyle mutfağınıza karakter katar.",
    features: [
      "Çok yüzeyli paslanmaz çelik rende",
      "Geniş ergonomik tutamak",
      "Dengeli kutu tabanı",
      "Canlı renk seçeneği",
      "Kolay temizlenebilir yüzey",
    ],
    materials: "Paslanmaz çelik rende yüzeyi, ABS gövde.",
    care: standardCare,
    dimensions: "11 × 9 × 24 cm",
    tags: ["rende", "kutu-rende", "star"],
    isNew: true,
  },
  {
    id: "srv-kal3001",
    imageCount: 6,
    name: "Lunar Kapaklı Kase 3'lü Set (1L · 2L · 3L)",
    category: "servis-sofra",
    subcategory: "salata-kaseleri",
    price: 339.99,
    stock: 30,
    rating: 4.8,
    reviewCount: 31,
    shortDescription:
      "Üç boy kapaklı Lunar kase; saklamadan servise tek sette.",
    description:
      "Lunar Kapaklı Kase 3'lü Set; 1, 2 ve 3 litrelik üç kaseyi sızdırmaz kapaklarıyla bir araya getirir. İç içe geçen tasarımıyla az yer kaplar; hazırlık, buzdolabında saklama ve servis için idealdir.",
    features: [
      "1 L, 2 L ve 3 L üç kase",
      "Sızdırmaz kapaklar",
      "İç içe geçen pratik saklama",
      "Buzdolabı ve dondurucuya uygun",
      "Servise hazır şık tasarım",
    ],
    materials: "Gıdayla temasa uygun polipropilen gövde ve kapak.",
    care: containerCare,
    dimensions: "Ø24 × 12 cm (en büyük kase)",
    tags: ["kase", "set", "lunar", "kapakli", "saklama"],
    isNew: true,
  },

  // ── Ev Gereçleri › Organizerlar ──────────────────────────────────
  {
    id: "org-ak499",
    imageCount: 0,
    name: "Piramit Kozmetik Ürün Düzenleyicisi",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 249.99,
    stock: 24,
    rating: 4.6,
    reviewCount: 0,
    shortDescription:
      "Piramit formlu çok gözlü kozmetik düzenleyici; tüm makyaj malzemeleriniz tek yerde.",
    description:
      "Piramit Kozmetik Ürün Düzenleyicisi, kademeli raf yapısıyla rujlar, fondötenler ve fırçalar için ayrı bölmeler sunar. Şeffaf tasarımı sayesinde aradığınızı anında bulursunuz.",
    features: [
      "Piramit kademeli tasarım",
      "Çok gözlü bölmeler",
      "Şeffaf gövde",
      "Kolay temizlenebilir yüzey",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "kozmetik", "piramit"],
    isNew: true,
  },
  {
    id: "org-ak500",
    imageCount: 0,
    name: "Podyum Kozmetik Ürün Düzenleyicisi",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 159.99,
    stock: 24,
    rating: 4.5,
    reviewCount: 0,
    shortDescription:
      "Podyum tarzı kompakt kozmetik düzenleyici; tezgâhınızda şık durur.",
    description:
      "Podyum Kozmetik Ürün Düzenleyicisi, yükseltilmiş platformuyla kozmetik ürünlerinizi sergiler gibi düzenler. Kompakt boyutuyla banyo tezgâhında az yer kaplar.",
    features: [
      "Yükseltilmiş podyum tasarım",
      "Kompakt boyut",
      "Kolay erişim",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "kozmetik", "podyum"],
    isNew: true,
  },
  {
    id: "org-ak503",
    imageCount: 0,
    name: "2'li Makyaj Organizer Set",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 169.99,
    stock: 12,
    rating: 4.7,
    reviewCount: 0,
    shortDescription:
      "İki parçadan oluşan makyaj organizer seti; yan yana veya ayrı kullanılabilir.",
    description:
      "2'li Makyaj Organizer Set, birbirini tamamlayan iki modülle makyaj malzemelerinizi düzenli tutar. Yan yana koyarak geniş bir düzenleme alanı oluşturabilir veya ayrı kullanabilirsiniz.",
    features: [
      "2 parçalı modüler tasarım",
      "Yan yana veya ayrı kullanım",
      "Çoklu bölmeler",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "makyaj", "set", "2li"],
    isNew: true,
  },
  {
    id: "org-ak504",
    imageCount: 0,
    name: "3'lü Makyaj Organizer Set",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 189.99,
    stock: 12,
    rating: 4.7,
    reviewCount: 0,
    shortDescription:
      "Üç parçalı makyaj organizer seti; geniş koleksiyon sahipleri için.",
    description:
      "3'lü Makyaj Organizer Set, üç ayrı modülüyle geniş makyaj koleksiyonlarını düzenli tutar. Fırçalar, rujlar ve bakım ürünleri için ayrı bölmeler sunar.",
    features: [
      "3 parçalı modüler tasarım",
      "Geniş düzenleme alanı",
      "Her modül ayrı kullanılabilir",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "makyaj", "set", "3lu"],
    isNew: true,
  },
  {
    id: "org-ak505",
    imageCount: 0,
    name: "Makyaj Pamukluğu",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 99.99,
    stock: 24,
    rating: 4.5,
    reviewCount: 0,
    shortDescription:
      "Kapaklı pamuk ve kulak çubuğu düzenleyicisi; banyonuzda hijyenik saklama.",
    description:
      "Makyaj Pamukluğu, kapaklı bölmeleriyle pamuk pedleri ve kulak çubuklarını toz ve nemden korur. Şık tasarımıyla banyo tezgâhında dekoratif bir aksesuar görevi görür.",
    features: [
      "Kapaklı hijyenik saklama",
      "Ayrı bölmeler",
      "Kompakt boyut",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "pamuk", "banyo"],
    isNew: true,
  },
  {
    id: "org-ak515",
    imageCount: 0,
    name: "4 Katlı Silindir Makyaj Organizeri",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 159.99,
    stock: 12,
    rating: 4.8,
    reviewCount: 0,
    shortDescription:
      "Döner silindir formunda 4 katlı makyaj organizeri; 360° erişim kolaylığı.",
    description:
      "4 Katlı Silindir Makyaj Organizeri, döner yapısıyla tüm makyaj malzemelerinize 360 derece erişim sağlar. Dört ayrı kat sayesinde ürünlerinizi kategorize edebilirsiniz.",
    features: [
      "360° döner silindir tasarım",
      "4 ayrı kat",
      "Geniş saklama kapasitesi",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "silindir", "4-katli", "doner"],
    isNew: true,
  },
  {
    id: "org-ak522",
    imageCount: 0,
    name: "Küçük Çekmece Modülü",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 149.99,
    stock: 24,
    rating: 4.6,
    reviewCount: 0,
    shortDescription:
      "Kompakt çekmeceli modül; küçük aksesuarlar ve makyaj malzemeleri için.",
    description:
      "Küçük Çekmece Modülü, çekmeceli yapısıyla mücevher, saç tokası ve küçük makyaj aksesuarlarınızı düzenli tutar. Tezgâh üstünde minimum yer kaplar.",
    features: [
      "Çekmeceli kompakt tasarım",
      "Küçük aksesuar saklama",
      "Minimum alan kullanımı",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "cekmece", "kucuk"],
    isNew: true,
  },
  {
    id: "org-ak523",
    imageCount: 0,
    name: "Çekmeceli Piramit Kozmetik Ürün Düzenleyicisi",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 329.99,
    stock: 12,
    rating: 4.8,
    reviewCount: 0,
    shortDescription:
      "Çekmeceli piramit düzenleyici; üstte açık bölmeler, altta çekmece.",
    description:
      "Çekmeceli Piramit Kozmetik Ürün Düzenleyicisi, piramit formlu üst bölmeleriyle sık kullandığınız ürünlere kolay erişim sağlarken, alt çekmecesiyle küçük aksesuarları gizli tutar.",
    features: [
      "Piramit üst bölmeler + alt çekmece",
      "Çift fonksiyonlu tasarım",
      "Geniş saklama alanı",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "piramit", "cekmece"],
    isNew: true,
  },
  {
    id: "org-ak634",
    imageCount: 0,
    name: "Üç Gözlü Çekmece",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 399.99,
    stock: 12,
    rating: 4.7,
    reviewCount: 0,
    shortDescription:
      "Üç gözlü çekmece sistemi; makyaj ve aksesuarlarınızı kategorize edin.",
    description:
      "Üç Gözlü Çekmece, üç ayrı çekmecesiyle makyaj malzemelerini, takıları ve aksesuarları kategorize etmenizi sağlar. Her çekmece bağımsız açılır ve kolayca temizlenir.",
    features: [
      "3 bağımsız çekmece",
      "Geniş saklama kapasitesi",
      "Kolay açma/kapama",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "cekmece", "3-gozlu"],
    isNew: true,
  },
  {
    id: "org-ak635",
    imageCount: 0,
    name: "Organizerli Üç Çekmeceli Set",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 499.99,
    stock: 8,
    rating: 4.9,
    reviewCount: 0,
    shortDescription:
      "Üst organizer + üç çekmeceli alt modül; komple makyaj istasyonu.",
    description:
      "Organizerli Üç Çekmeceli Set, üst kısmındaki açık organizerle sık kullanılan ürünlere anında erişim sağlarken, üç katlı çekmece sistemiyle geniş bir saklama alanı sunar.",
    features: [
      "Üst açık organizer bölümü",
      "3 katlı çekmece sistemi",
      "Komple makyaj istasyonu",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "cekmece", "set", "istasyon"],
    isNew: true,
  },
  {
    id: "org-ak730",
    imageCount: 0,
    name: "Yuvarlak İkili Organizer",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 249.99,
    stock: 24,
    rating: 4.6,
    reviewCount: 0,
    shortDescription:
      "Yuvarlak formlu iki parçalı organizer; fırçalar ve kozmetik için.",
    description:
      "Yuvarlak İkili Organizer, silindirik iki modülüyle makyaj fırçalarını ve kozmetik ürünlerini şık biçimde düzenler. Yuvarlak formu tezgâhta hoş bir görünüm sağlar.",
    features: [
      "2 parçalı yuvarlak tasarım",
      "Fırça ve kozmetik bölmeleri",
      "Şık silindirik form",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "yuvarlak", "ikili"],
    isNew: true,
  },
  {
    id: "org-ak731",
    imageCount: 0,
    name: "Mücevher Kutusu",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 399.99,
    stock: 12,
    rating: 4.8,
    reviewCount: 0,
    shortDescription:
      "Çok bölmeli mücevher kutusu; yüzük, kolye ve küpeleriniz için özel gözler.",
    description:
      "Mücevher Kutusu, kadife kaplı iç bölmeleriyle yüzük, kolye, bileklik ve küpelerinizi çizilmeden saklar. Şeffaf kapağı sayesinde içeriği görebilirsiniz.",
    features: [
      "Çok bölmeli iç yapı",
      "Yüzük, kolye, küpe bölmeleri",
      "Şeffaf kapaklı tasarım",
      "Dekoratif görünüm",
    ],
    materials: "Akrilik gövde, kadife iç astar.",
    care: "Nemli bezle silin. Kadife kısmı kuru fırçayla temizleyin.",
    tags: ["organizer", "mucevher", "kutu", "taki"],
    isNew: true,
  },
  {
    id: "org-ak766",
    imageCount: 0,
    name: "Aynalı 4 Katlı Kare Organizer",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 189.99,
    stock: 12,
    rating: 4.7,
    reviewCount: 0,
    shortDescription:
      "Aynalı kapaklı, 4 katlı kare organizer; makyaj yaparken ayna elinizin altında.",
    description:
      "Aynalı 4 Katlı Kare Organizer, üst kapağındaki ayna ile makyaj yaparken ekstra aksesuar ihtiyacını ortadan kaldırır. Dört katlı döner yapısıyla geniş saklama sunar.",
    features: [
      "Üst kapakta entegre ayna",
      "4 katlı döner yapı",
      "Kare kompakt form",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik, cam ayna.",
    care: "Nemli bezle silin. Aynayı cam temizleyiciyle silin.",
    tags: ["organizer", "aynali", "4-katli", "kare"],
    isNew: true,
  },
  {
    id: "org-ak865",
    imageCount: 0,
    name: "Premium Makyaj Organizeri",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 899.99,
    stock: 4,
    rating: 4.9,
    reviewCount: 0,
    shortDescription:
      "Büyük boy premium makyaj organizeri; profesyonel koleksiyonlar için tasarlandı.",
    description:
      "Premium Makyaj Organizeri, çok sayıda bölme, çekmece ve açık raf sistemiyle profesyonel makyaj koleksiyonlarını eksiksiz düzenler. Geniş kapasitesi ve sağlam yapısıyla uzun ömürlüdür.",
    features: [
      "Profesyonel geniş kapasite",
      "Çekmece + açık raf kombinasyonu",
      "Çok bölmeli tasarım",
      "Dayanıklı kalın akrilik",
    ],
    materials: "Premium kalınlıkta şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "premium", "profesyonel", "buyuk"],
    isNew: true,
  },
  {
    id: "org-ak869",
    imageCount: 0,
    name: "7 Gözlü Makyaj Organizeri",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 229.99,
    stock: 12,
    rating: 4.7,
    reviewCount: 0,
    shortDescription:
      "7 ayrı gözlü makyaj organizeri; her ürün grubuna özel bölme.",
    description:
      "7 Gözlü Makyaj Organizeri, yedi farklı boyutta bölmesiyle ruj, far, fondöten, fırça ve daha fazlasını ayrı ayrı düzenlemenizi sağlar.",
    features: [
      "7 farklı boyutta göz",
      "Her ürün grubuna özel bölme",
      "Pratik düzenleme",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "7-gozlu", "makyaj"],
    isNew: true,
  },
  {
    id: "org-mtaki",
    imageCount: 0,
    name: "Takı Organizeri",
    topCategory: "genel-ev-urunleri",
    category: "organizerlar",
    price: 159.99,
    stock: 24,
    rating: 4.6,
    reviewCount: 0,
    shortDescription:
      "Kompakt takı organizeri; yüzük, küpe ve bilekliklerinizi düzenli saklayın.",
    description:
      "Takı Organizeri, özel bölmeleriyle yüzük, küpe, kolye ve bilekliklerinizi karışmadan saklar. Kompakt boyutuyla çekmece içi veya tezgâh üstü kullanıma uygundur.",
    features: [
      "Takı türlerine göre özel bölmeler",
      "Kompakt boyut",
      "Çekmece içi veya tezgâh üstü kullanım",
      "Şeffaf gövde",
    ],
    materials: "Şeffaf akrilik.",
    care: "Nemli bezle silin. Alkol bazlı temizleyicilerden kaçının.",
    tags: ["organizer", "taki", "yuzuk", "kupe"],
    isNew: true,
  },
];

const buildImages = (id: string, count: number) =>
  Array.from({ length: count }, (_, i) => `/products/${id}/${i}.jpg`);

// Prefer the generated manifest; fall back to the seed's imageCount.
const imagesFor = (id: string, count: number) => {
  const fromManifest = IMAGE_MANIFEST[id];
  return fromManifest && fromManifest.length > 0
    ? fromManifest
    : buildImages(id, count);
};

const ensureSlug = (s: string) => slugify(s);

const DEFAULT_TOP_CATEGORY = "mutfak";
const PLACEHOLDER_IMAGE = "/placeholder-product.svg";

const FINE_SUBCATEGORY_LABELS: Record<string, string> = {
  "vakumlu-kavanozlar": "Vakumlu Kavanozlar",
  "dikdortgen-kaplar": "Dikdörtgen Kaplar",
  "cam-gorunumlu": "Cam Görünümlü Kaplar",
  "ahsap-kapakli": "Ahşap Kapaklı Kavanozlar",
  "saklama-setleri": "Saklama Setleri",
  "manuel-dograyicilar": "Manuel Doğrayıcılar",
  "el-rondolari": "El Rondoları",
  "ipli-dograyicilar": "İpli Doğrayıcılar",
  "mandolin-dilimleyiciler": "Mandolin Dilimleyiciler",
  "cok-yonlu-rendeler": "Çok Yönlü Rendeler",
  "profesyonel-setler": "Profesyonel Setler",
  "salata-kaseleri": "Salata & Servis Kaseleri",
  "servis-tabaklari": "Servis Tabakları",
  "surahi-karaf": "Sürahi & Karaflar",
  "spatula-kepce-setleri": "Spatula & Kepçe Setleri",
  "olcu-kaplari": "Ölçü Kapları",
  "salata-kurutucular": "Salata Kurutucular",
  "kesme-tahtalari": "Kesme Tahtaları",
  "soyacaklar": "Soyacaklar",
  "havluluk-standlar": "Havluluk & Standlar",
  "buz-kaliplari": "Buz Kalıpları",
};

export const products: Product[] = seeds.map((seed) => {
  const topSlug = seed.topCategory ?? DEFAULT_TOP_CATEGORY;
  const cat = categoryMap[topSlug];
  if (!cat) throw new Error(`Unknown category: ${topSlug}`);
  const subSlug = seed.category;
  const sub = cat.subcategories.find((x) => x.slug === subSlug);

  const images = imagesFor(seed.id, seed.imageCount);
  const cover = images[0] ?? PLACEHOLDER_IMAGE;
  const discountPercent = seed.originalPrice
    ? Math.round(
        ((seed.originalPrice - seed.price) / seed.originalPrice) * 100,
      )
    : undefined;

  // Keep the former fine-grained grouping searchable via tags.
  const fineLabel = seed.subcategory
    ? FINE_SUBCATEGORY_LABELS[seed.subcategory]
    : undefined;
  const tags = [
    ...(seed.tags ?? []),
    ...(seed.subcategory ? [seed.subcategory] : []),
    ...(fineLabel ? [fineLabel] : []),
  ];

  return {
    id: seed.id,
    slug: ensureSlug(seed.name),
    name: seed.name,
    shortDescription: seed.shortDescription,
    description: seed.description,
    price: seed.price,
    originalPrice: seed.originalPrice,
    discountPercent,
    category: topSlug,
    categoryLabel: cat.label,
    subcategory: subSlug,
    subcategoryLabel: sub?.label,
    brand: "Zest Home",
    sku: `ZST-${seed.id.toUpperCase()}`,
    stock: seed.stock,
    rating: seed.rating,
    reviewCount: seed.reviewCount,
    imageUrl: cover,
    images,
    tags,
    features: seed.features,
    materials: seed.materials,
    care: seed.care,
    dimensions: seed.dimensions,
    isNew: seed.isNew,
    isBestSeller: seed.isBestSeller,
    isFeatured: seed.isFeatured,
  } satisfies Product;
});

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const getProductsByCategory = (slug: string) =>
  products.filter((p) => p.category === slug);

export const getRelatedProducts = (product: Product, max = 4): Product[] => {
  const sameSub = products.filter(
    (p) =>
      p.id !== product.id &&
      p.subcategory &&
      p.subcategory === product.subcategory,
  );
  const sameCat = products.filter(
    (p) => p.id !== product.id && p.category === product.category,
  );
  const seen = new Set<string>();
  const out: Product[] = [];
  for (const list of [sameSub, sameCat]) {
    for (const p of list) {
      if (out.length >= max) break;
      if (seen.has(p.id)) continue;
      seen.add(p.id);
      out.push(p);
    }
  }
  return out;
};

export const featuredProducts = products.filter((p) => p.isFeatured);
export const bestSellers = products.filter((p) => p.isBestSeller);
export const newArrivals = products.filter((p) => p.isNew);
export const discountedProducts = products.filter(
  (p) => (p.discountPercent ?? 0) > 0,
);
